apiVersion: v1
version: 6.0.0-bb.7
appVersion: 6.0.0
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- https://github.com/stefanprodan/podinfo
kubeVersion: ">=1.19.0-0"
dependencies:
- name: gluon
  version: "0.2.10"
  repository: "oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon"
