name: "Comment test"
on:
  pull_request_review:
    types: [submitted]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - name: Mirror + trigger CI
         uses: DoD-Platform-One/gitlab-mirror-and-ci-action@master
         with:
           args: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/podinfo.git
         env:
           FORCE_PUSH: "false"
           GITLAB_HOSTNAME: "repo1.dso.mil"
           GITLAB_USERNAME: "snekcode"
           GITLAB_PASSWORD: ${{ secrets.GITLAB_ACCESS_TOKEN }}
           GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
           GITHUB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
